[project]
name = "local-rag"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "ollama>=0.6.2",
    "pandas>=3.0.5",
    "pyyaml>=6.0.3",
    "qdrant-client>=1.19.0",
    "sentence-transformers>=6.0.1",
]

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
    "langchain-core>=1.6.2",
    "langchain-ollama>=1.1.0",
    "openai>=3.8.0",
    "pytest>=9.1.1",
    "ruff>=0.16.6",
]
